// lang.js — translations for Hindi, Marathi, English
const Lang = {
  hi: {
    welcome: "स्वागत है!",
    quote: "किसान ही देश की रीढ़ है – स्मार्ट खेती, उज्ज्वल भविष्य!",
    selectLanguage: "भाषा चुनें",
    continue: "जारी रखें",
    dashboard: "मुख्य डैशबोर्ड",
    goodMorning: "सुप्रभात",
    notifications: "सूचनाएं",
    choosePath: "अपना रास्ता चुनें",
    soilAnalysis: "मिट्टी विश्लेषण",
    diseaseDetection: "रोग पहचान",
    askAI: "AI से पूछें",
    community: "समुदाय",
    knowledge: "ज्ञान केंद्र",
  },
  mr: {
    welcome: "स्वागत आहे!",
    quote: "शेतकरी हाच देशाचा कणा – स्मार्ट शेती, उज्ज्वल भविष्य!",
    selectLanguage: "भाषा निवडा",
    continue: "पुढे चला",
    dashboard: "मुख्य डॅशबोर्ड",
    goodMorning: "शुभ सकाळ",
    notifications: "सूचना",
    choosePath: "आपला मार्ग निवडा",
    soilAnalysis: "माती विश्लेषण",
    diseaseDetection: "रोग निदान",
    askAI: "AI ला विचारा",
    community: "समुदाय",
    knowledge: "ज्ञान केंद्र",
  },
  en: {
    welcome: "Welcome!",
    quote: "Farmers are the backbone of our nation – Smart Farming, Bright Future!",
    selectLanguage: "Select Language",
    continue: "Continue",
    dashboard: "Main Dashboard",
    goodMorning: "Good Morning",
    notifications: "Notifications",
    choosePath: "Choose Your Path",
    soilAnalysis: "Soil Analysis",
    diseaseDetection: "Disease Detection",
    askAI: "Ask AI",
    community: "Community",
    knowledge: "Knowledge Center",
  }
};
