// lang.js - translations (hi, mr, en) from original file
const LANG = {
  hi: {
    voicePrompt: "नमस्ते! मुझे अपने खेत के बारे में बताएं, और मैं आपका मार्गदर्शन करूंगा।",
    quote: "किसान ही देश की रीढ़ है – स्मार्ट खेती, उज्ज्वल भविष्य!",
    selectLanguage: "भाषा चुनें",
    continue: "जारी रखें",
    skipToSetup: "सेटअप पर जाएं",
    mainDashboard: "मुख्य डैशबोर्ड",
    goodMorning: "सुप्रभात",
    notifications: "सूचनाएं",
    choosePath: "अपना रास्ता चुनें:",
    soilAnalysis: "मिट्टी विश्लेषण",
    diseaseDetection: "रोग पहचान",
    quickActions: "त्वरित कार्रवाइयां",
    askAI: "AI से पूछें",
    community: "समुदाय",
    knowledge: "ज्ञान केंद्र",
    learnNewTechniques: "खेती की नई तकनीकें और टिप्स सीखें",
    watchVideo: "वीडियो देखें",
    farmSetupTitle: "खेत की जानकारी सेटअप",
    farmLocation: "खेत का स्थान",
    gpsAutoDetect: "GPS ऑटो-डिटेक्ट",
    manual: "मैन्युअल",
    locationDetected: "स्थान पता चला:",
    landDetails: "भूमि का विवरण",
    acre: "एकड़",
    hectare: "हेक्टेयर",
    irrigationSource: "सिंचाई का स्रोत",
    borewell: "बोरवेल", canal: "नहर", rainFed: "वर्षा-आधारित",
    dripIrrigation: "ड्रिप सिंचाई",
    waterAvailability: "पानी की उपलब्धता",
    low: "कम", medium: "मध्यम", high: "उच्च",
    budgetOptional: "बजट (वैकल्पिक)",
    perSeason: "प्रति सीजन",
    saveAndContinue: "सहेजें और जारी रखें",
    lastSeason: "पिछला सीजन",
    viewDetailedPlan: "विस्तृत योजना देखें",
    detailedPlanFor: "के लिए विस्तृत योजना",
    forecast: "पूर्वानुमान",
    yield: "उपज",
    marketDemand: "बाजार की मांग",
    profit: "मुनाफा",
    costBreakdown: "लागत का विवरण",
    seeds: "बीज",
    fertilizer: "उर्वरक",
    labor: "श्रम",
    waterMisc: "पानी और अन्य",
    netProfit: "शुद्ध लाभ",
    rationale: "तर्क",
    whyThisCrop: "यह फसल क्यों?",
    cultivationGuide: "खेती गाइड",
    planting: "रोपण",
    fertilizers: "उर्वरक",
    pestControl: "कीट नियंत्रण",
    resourceCalculator: "संसाधन कैलकुलेटर",
    yourLandSize: "आपकी जमीन का आकार (एकड़ में)",
    calculate: "गणना",
    requiredSeeds: "आवश्यक बीज",
    requiredFertilizer: "आवश्यक उर्वरक",
    govtSchemes: "सरकारी योजनाएं",
    callExpert: "विशेषज्ञ को कॉल करें",
    buyMedicine: "दवा खरीदें",
    backToDashboard: "डैशबोर्ड पर वापस जाएं",
    loadingData: "डेटा लोड हो रहा है..."
  },
  mr: {
    voicePrompt: "नमस्कार! मला तुमच्या शेताबद्दल सांगा, आणि मी तुम्हाला मार्गदर्शन करेन.",
    quote: "शेतकरी हाच देशाचा कणा – स्मार्ट शेती, उज्ज्वल भविष्य!",
    selectLanguage: "भाषा निवडा",
    continue: "पुढे जा",
    skipToSetup: "सेटअपवर जा",
    mainDashboard: "मुख्य डॅशबोर्ड",
    goodMorning: "शुभ सकाळ",
    notifications: "सूचना",
    choosePath: "आपला मार्ग निवडा:",
    soilAnalysis: "माती विश्लेषण",
    diseaseDetection: "रोग ओळख",
    quickActions: "द्रुत क्रिया",
    askAI: "AI ला विचारा",
    community: "समुदाय",
    knowledge: "ज्ञान केंद्र",
    learnNewTechniques: "नवीन शेती तंत्र आणि टिप्स शिका",
    watchVideo: "व्हिडिओ पहा",
    farmSetupTitle: "शेती प्रोफाइल सेटअप",
    farmLocation: "शेताचे ठिकाण",
    gpsAutoDetect: "GPS ऑटो-डिटेक्ट",
    manual: "मॅन्युअल",
    locationDetected: "ठिकाण आढळले:",
    landDetails: "जमिनीचा तपशील",
    acre: "एकर", hectare: "हेक्टर",
    irrigationSource: "सिंचनाचा स्रोत",
    borewell: "बोरवेल", canal: "कालवा", rainFed: "पावसावर अवलंबून",
    dripIrrigation: "ठिबक सिंचन",
    waterAvailability: "पाण्याची उपलब्धता",
    low: "कमी", medium: "मध्यम", high: " जास्त",
    budgetOptional: "बजेट (ऐच्छिक)",
    perSeason: "प्रति हंगाम",
    saveAndContinue: "जतन करा आणि पुढे जा",
    lastSeason: "मागील हंगाम",
    viewDetailedPlan: "तपशीलवार योजना पहा",
    detailedPlanFor: "साठी तपशीलवार योजना",
    forecast: "अंदाज",
    yield: "उत्पन्न",
    marketDemand: "बाजारातील मागणी",
    profit: "नफा",
    costBreakdown: "खर्चाचे विवरण",
    seeds: "बियाणे",
    fertilizer: "खत",
    labor: "मजुरी",
    waterMisc: "पाणी आणि इतर",
    netProfit: "निव्वळ नफा",
    rationale: "तर्क",
    whyThisCrop: "हे पीक का?",
    cultivationGuide: "लागवड मार्गदर्शक",
    planting: "लागवड",
    fertilizers: "खत",
    pestControl: "कीड नियंत्रण",
    resourceCalculator: "संसाधन कॅल्क्युलेटर",
    yourLandSize: "तुमच्या जमिनीचे क्षेत्रफळ (एकरमध्ये)",
    calculate: "गणना",
    requiredSeeds: "आवश्यक बियाणे",
    requiredFertilizer: "आवश्यक खत",
    govtSchemes: "सरकारी योजना",
    callExpert: "तज्ञांना कॉल करा",
    buyMedicine: "औषध खरेदी करा",
    backToDashboard: "डॅशबोर्डवर परत जा",
    loadingData: "डेटा लोड होत आहे..."
  },
  en: {
    voicePrompt: "Hi! Tell me about your farm, and I'll guide you.",
    quote: "Farmers are the backbone of our nation – Smart Farming, Bright Future!",
    selectLanguage: "Select Language",
    continue: "Continue",
    skipToSetup: "Skip to Setup",
    mainDashboard: "Main Dashboard",
    goodMorning: "Good Morning",
    notifications: "Notifications",
    choosePath: "Choose Your Path:",
    soilAnalysis: "Soil Analysis",
    diseaseDetection: "Disease Detection",
    quickActions: "Quick Actions",
    askAI: "Ask AI",
    community: "Community",
    knowledge: "Knowledge Center",
    learnNewTechniques: "Learn new farming techniques and tips",
    watchVideo: "Watch Video",
    farmSetupTitle: "Farm Profile Setup",
    farmLocation: "Farm Location",
    gpsAutoDetect: "GPS Auto-detect",
    manual: "Manual",
    locationDetected: "Location detected:",
    landDetails: "Land Details",
    acre: "Acre", hectare: "Hectare",
    irrigationSource: "Irrigation Source",
    borewell: "Borewell", canal: "Canal", rainFed: "Rain-fed",
    dripIrrigation: "Drip Irrigation",
    waterAvailability: "Water Availability",
    low: "Low", medium: "Medium", high: "High",
    budgetOptional: "Budget (Optional)",
    perSeason: "per season",
    saveAndContinue: "Save & Continue",
    lastSeason: "Last Season",
    viewDetailedPlan: "View Detailed Plan",
    detailedPlanFor: "Detailed Plan for",
    forecast: "Forecast",
    yield: "Yield",
    marketDemand: "Market Demand",
    profit: "Profit",
    costBreakdown: "Cost Breakdown",
    seeds: "Seeds",
    fertilizer: "Fertilizer",
    labor: "Labor",
    waterMisc: "Water & Misc.",
    netProfit: "Net Profit",
    rationale: "Rationale",
    whyThisCrop: "Why this Crop?",
    cultivationGuide: "Cultivation Guide",
    planting: "Planting",
    fertilizers: "Fertilizers",
    pestControl: "Pest Control",
    resourceCalculator: "Resource Calculator",
    yourLandSize: "Your Land Size (in acres)",
    calculate: "Calculate",
    requiredSeeds: "Required Seeds",
    requiredFertilizer: "Required Fertilizer",
    govtSchemes: "Government Schemes",
    callExpert: "Call Expert",
    buyMedicine: "Buy Medicine",
    backToDashboard: "Back to Dashboard",
    loadingData: "Loading Data..."
  }
};
